version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bets-db
    environment:
      POSTGRES_DB: bets
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env

  spring-bet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-bet-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bets-db:5432/bets
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.yaml
    networks:
      - app-network
    ports:
      - "443:443"
    volumes:
      - ./db/changelog:/app/db/changelog
      - ./logs:/app/logs
      - /etc/letsencrypt:/etc/letsencrypt
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
